MENU_TOP_ROW = 0
MENU_TOP_COL = 0
MENU_WIDTH = 80
MENU_HEIGHT = 3
MENU_BOTTOM_ROW = MENU_TOP_ROW + MENU_HEIGHT
MENU_BOTTOM_COL = MENU_TOP_ROW + MENU_WIDTH

PLAYER_H_TOP_ROW =  MENU_BOTTOM_ROW
PLAYER_H_TOP_COL =  MENU_TOP_COL
PLAYER_H_HEIGHT=15
PLAYER_H_WIDTH= MENU_WIDTH//2-3
PLAYER_H_BOTTOM_ROW = PLAYER_H_TOP_ROW+PLAYER_H_HEIGHT
PLAYER_H_BOTTOM_COL = PLAYER_H_TOP_COL+PLAYER_H_WIDTH

PLAYER_M_TOP_ROW =  PLAYER_H_TOP_ROW
PLAYER_M_TOP_COL =  PLAYER_H_BOTTOM_COL +3
PLAYER_M_HEIGHT=PLAYER_H_HEIGHT
PLAYER_M_WIDTH=PLAYER_H_WIDTH
PLAYER_M_BOTTOM_ROW = PLAYER_M_TOP_ROW+PLAYER_M_HEIGHT
PLAYER_M_BOTTOM_COL = PLAYER_M_TOP_COL+PLAYER_M_WIDTH


PLAYER_H_KEYS = 122, 100, 115, 113 #z, d, s, q
PLAYER_M_KEYS = 259, 261, 258, 260 #UP, RIGHT, DOWN, LEFT


